---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simwork
spec:
  selector:
    matchLabels:
      app: simwork
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: simwork
    spec:
      containers:
      - name: simwork
        image: asia.gcr.io/labs-169405/simwork:v1
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            # cpu: 1000m
            memory: 500Mi
        imagePullPolicy: Always
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simwork-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simwork
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
